blank_issues_enabled: false
contact_links:
  - name: Questions & Discussions
    url: https://github.com/alovajs/alova/discussions
    about: Use GitHub discussions for your questions and discussions.