name: Publish Alova

# 触发条件：在 push或合并请求 到 master 或 realease开头的分支后
on:
  push:
    branches:
      - main
      - 'release/**'
  pull_request:
    branches:
      - main
      - 'release/**'

# 任务
jobs:
  Publish:
    # 服务器环境：最新版 Ubuntu
    runs-on: ubuntu-latest
    steps:
      # 拉取代码
      - name: Checkout
        uses: actions/checkout@v3
      - name: Use Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 16.14.x
          cache: 'npm'

      # 执行测试和打包操作
      - run: npm ci
      - run: npm run build --if-present
      - run: npm run test
      - run: npm run coveralls
      - run: npm publish
        env: 
          NODE_AUTH_TOKEN: ${{ secrets.NPM_ALOVA_PUBLISH_TOKEN }}
